"""
SDL_intrin.h
Compiler Intrinsics Detection
Document: https://wiki.libsdl.org/SDL3/CategoryIntrinsics
"""

import ctypes

from sdl3_ctypes.lib import libsdl3

# #define SDL_ALTIVEC_INTRINSICS 1
SDL_ALTIVEC_INTRINSICS = 1
# #define SDL_AVX2_INTRINSICS 1
SDL_AVX2_INTRINSICS = 1
# #define SDL_AVX512F_INTRINSICS 1
SDL_AVX512F_INTRINSICS = 1
# #define SDL_AVX_INTRINSICS 1
SDL_AVX_INTRINSICS = 1
# #define SDL_LASX_INTRINSICS 1
SDL_LASX_INTRINSICS = 1
# #define SDL_LSX_INTRINSICS 1
SDL_LSX_INTRINSICS = 1
# #define SDL_MMX_INTRINSICS 1
SDL_MMX_INTRINSICS = 1
# #define SDL_NEON_INTRINSICS 1
SDL_NEON_INTRINSICS = 1
# #define SDL_SSE2_INTRINSICS 1
SDL_SSE2_INTRINSICS = 1
# #define SDL_SSE3_INTRINSICS 1
SDL_SSE3_INTRINSICS = 1
# #define SDL_SSE4_1_INTRINSICS 1
SDL_SSE4_1_INTRINSICS = 1
# #define SDL_SSE4_2_INTRINSICS 1
SDL_SSE4_2_INTRINSICS = 1
# #define SDL_SSE_INTRINSICS 1
SDL_SSE_INTRINSICS = 1
# #define SDL_TARGETING(x) __attribute__((target(x)))
